# Dataset configuration for point cloud data
data:
  _target_: michelangelo.datasets.PointCloudDataModule
  data_dir: ${data_dir}  # Will be set via command line
  batch_size: 32
  num_workers: 8
  num_points: 4096
  num_volume_samples: 8192
  num_near_samples: 2048
  train_val_test_split: [0.8, 0.1, 0.1]
  
  # Data augmentation
  train_transform:
    _target_: michelangelo.data.transforms.Compose
    transforms:
      - _target_: michelangelo.data.transforms.AxisScaleTransform
        interval: [0.9, 1.1]
        jitter: true
        jitter_scale: 0.01
      - _target_: michelangelo.data.transforms.ToTensor
  
  val_transform:
    _target_: michelangelo.data.transforms.Compose
    transforms:
      - _target_: michelangelo.data.transforms.ToTensor
  
  test_transform:
    _target_: michelangelo.data.transforms.Compose
    transforms:
      - _target_: michelangelo.data.transforms.ToTensor
